#
# PARAMETERS: General parameters
#
General:

  # Number of works in parallel. Othwerise is the 75% of total number of cpu's
  # n_cpu: 8

  # Comparison groups:
  # - pair groups for hypothesis testing (LimmaCompare)
  # - pair groups to which calculate FDR (FDRoptimizer)
  # - pair groups to plot the PTM maps (PTMmap)
  # - pair groups to to be analysed (qReport)
  groups:
    - [ Heteroplasmy, Control ]

  # Significance value used across multiple modules. Can be either a qvalue or pvalue. Defaults to pvalue.
  significance_value: 'qvalue'



#
# PARAMETERS: NMpyCompare.py
#
NMpyCompare:



#
# PARAMETERS: LIMMA wo GUI
#
LimmaCompare:

  # Possible types 
  # - limma
  # - limma_with_duplicates
  # - t-test
  test_type:
    - limma
    - t-test




#
# PARAMETERS: FDRoptimizer.py
#
FDRoptimizer:

  # FDR thresholds applied
  FDR_Thr:
    - 0.01
    - 0.05

  # Scan frequency window
  Window: [0, 50]

  # Add column with FDR of at maximum value
  AddFDR: True



#
# PARAMETERS: PTMMap
#
PTMMap:

  # Plot parameters
  font_size: 50
  grid: 'No'
  plot_width: 1700
  plot_height: 850

  # How Non-modified are named
  NM: NM


  # Threshold of filtering for the given integrations: pgm2p_NM, pgm2p, p2qc, qc2q
  threshold_pgm2p_NM: 0.05
  threshold_pgm2p: 0.05
  threshold_p2qc: 0.05
  threshold_qc2q: 0.05
  pgmFreqThreshold: 0

  # List of selected proteins to plot
  # Leave blank to plot all proteins
  selected_proteins: []



#
# PARAMETERS: qReportMaker
#
qReportMaker:

  # FDR threshold used
  qvThr: [0.01, 0.05, 0.1, 1]


  #
  # PTM Frequency Table options
  #

  # Window size used to estimate probability
  x: 5

  # q-value column used to filter PTM (aa, dm)
  # Possible values: 'binom1-PSM', 'binom1-PDM', 'binom2-PSM', 'binom2-PDM'
  binom: binom1-PSM

  # Binomial q-value threshold applied to filter PTM
  q_thr: 0.01

  # Values represented in pivot table
  # Possible values: 'x-PSM', 'x-PDM'
  values_pivot: x-PSM

