#
# PARAMETERS: NMpyCompare.py
#
NMpyCompare:



#
# PARAMETERS: LIMMA wo GUI
#
LimmaCompare:

  # Possible types 
  # - limma
  # - limma_with_duplicates
  # - t-test
  test_type:
    - limma
    - t-test

  hypothesis_testing:
    - [ H, C ]



#
# PARAMETERS: FDRoptimizer.py
#
FDRoptimizer:

  # Pair groups to which calculate FDR
  groups:
    - H-C

  # FDR thresholds applied
  FDR_Thr:
    - 0.01
    - 0.05

  # Scan frequency window
  Window: [0, 50]

  # Add column with FDR of at maximum value
  AddFDR: True



#
# PARAMETERS: PTMMap
#
PTMMap:

  # Plot parameters
  font_size: 50
  grid: No
  plot_width: 1700
  plot_height: 850

  # How Non-modified are named
  NM: NM

  # Group to be analysed
  groups:
    - H-C

  # Threshold of filtering for the given integrations: pgm2p_NM, pgm2p, p2qf, qf2q
  threshold_pgm2p_NM: 0.05
  threshold_pgm2p: 0.05
  threshold_p2qf: 0.05
  threshold_qf2q: 0.05
  pgmFreqThreshold: 0



#
# PARAMETERS: qReportMaker
#
qReportMaker:

  # FDR threshold used
  qvThr:
    - 0.01
    - 0.05
    - 0.1

  # Group contrasts to be analysed
  groups:
    - H-C

  #
  # PTM Frequency Table options
  #

  # Window size used to estimate probability
  x: 5

  # q-value column used to filter PTM (aa, dm)
  # Possible values: 'binom1-PSM', 'binom1-PDM', 'binom2-PSM', 'binom2-PDM'
  binom: binom1-PSM

  # Binomial q-value threshold applied to filter PTM
  q_thr: 0.01

  # Values represented in pivot table
  # Possible values: 'x-PSM', 'x-PDM'
  values_pivot: x-PSM

